### ISSUE TITLE
help

### ISSUE THREAD

**Issue by Tempest-101** [Natasha-R/Federated-Learning-Sparsification#1]
when i try to run "python simulation.py --dataset_name="cifar" --approach="topk" --sparsify_by=0.1 --num_rounds=180", it shows Exception that 'bytes' object has no attribute 'pop'

**Comment by Natasha-R** [comment]
I was not able to replicate your issue. Have you tried using some of the functions individually, to try identify the exact source of the problem?

**Comment by Simon007-heiyewuxing** [comment]
I have met the same problem with **flwr**'s version==1.8.0, too. But when I run it with flwr==1.6.0, everything will be fine. It seems that some update between versions of flwr caused this problem.

**Comment by Natasha-R** [comment]
> I have met the same problem with **flwr**'s version==1.8.0, too. But when I run it with flwr==1.6.0, everything will be fine. It seems that some update between versions of flwr caused this problem.

A big thanks for figuring that out. I have updated the repo accordingly to indicate the working flwr version to use.
